using System;

namespace CamillaDsp.Client
{
    public enum Methods
    {
        // Get methods
        GetVersion,
        GetUpdateInterval,
        GetState,
        GetStopReason,
        GetCaptureRate,
        GetSignalRange,
        GetRateAdjust,
        GetBufferLevel,
        GetClippedSamples,
        ResetClippedSamples,
        GetProcessingLoad,
        GetStateFilePath,
        GetStateFileUpdated,
        GetSupportedDeviceTypes,
        GetCaptureSignalPeak,
        GetCaptureSignalRms,
        GetPlaybackSignalPeak,
        GetPlaybackSignalRms,
        GetCaptureSignalPeakSince,
        GetCaptureSignalRmsSince,
        GetPlaybackSignalPeakSince,
        GetPlaybackSignalRmsSince,
        GetCaptureSignalPeakSinceLast,
        GetCaptureSignalRmsSinceLast,
        GetPlaybackSignalPeakSinceLast,
        GetPlaybackSignalRmsSinceLast,
        GetSignalLevels,
        GetSignalLevelsSince,
        GetSignalLevelsSinceLast,
        GetSignalPeaksSinceStart,
        ResetSignalPeaksSinceStart,
        GetVolume,
        GetMute,
        ToggleMute,
        GetFaderVolume,
        GetAvailableCaptureDevices,
        GetAvailablePlaybackDevices,
        GetFaderMute,
        ToggleFaderMute,
        GetFaders,
        GetConfig,
        GetConfigJson,
        GetConfigTitle, 
        GetConfigDescription,
        GetConfigFilePath,
        GetPreviousConfig,
        Reload,
        Stop,
        Exit,
        ReadConfig,
        ReadConfigFile,
        ValidateConfig,
        
        // Set methods
        SetUpdateInterval,
        SetVolume,
        AdjustVolume,
        SetMute,
        SetFaderVolume,
        SetFaderExternalVolume,
        AdjustFaderVolume,
        SetFaderMute,
        SetConfigFilePath,
        SetConfig,
        SetConfigJson
    }
}
